sudo: false

language: php

dist: trusty

php:
    - "hhvm"

before_script:
    - composer install --prefer-source

script:
    - hh_server --check .
    - ./vendor/bin/phpunit -c t/phpunit.xml t/
before_install:
    - composer install
